name: vanity_app
description: A new Flutter project for Vanity Enterprises.

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5

  # Add other dependencies here
